baseURL = "https://devopsbrain.ru"
languageCode = "en-us"
title = "DevOps Brain"
theme="archie"
copyright = "© It Cat"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Твердо и четко - [телега](https://t.me/devopsbrain)"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[menu.main]]
name = "На главную"
url = "/"
weight = 1

[[menu.main]]
name = "Посты"
url = "/posts"
weight = 2

[[menu.main]]
name = "Об авторе"
url = "/about"
weight = 3

[[menu.main]]
name = "Теги"
url = "/tags"
weight = 4
