baseURL = "https://devopsbrain.ru"
languageCode = "en-us"
title = "DevOps Brain"
theme="archie"
copyright = "© It Cat"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Твердо и четко - [телега](https://t.me/devopsbrain)"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/itcaat"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/itcaat"

[[params.social]]
name = "Telegram"
icon = "telegram"
url = "https://t.me/devopsbrain"

[[menu.main]]
name = "Список публикаций"
url = "/posts"
weight = 2

[[menu.main]]
name = "Категории"
url = "/tags"
weight = 3

[[menu.main]]
name = "Пет-проекты"
url = "/tags/pet-projects/"
weight = 4

[[menu.main]]
name = "Об авторе"
url = "/cv"
weight = 5


